### ISSUE TITLE
可以支持一下docker compose吗

### ISSUE THREAD

**Issue by everett7623** [nicejade/markdown-online-editor#90]
可以支持一下docker compose吗，方便管理啊，谢谢

**Comment by TopGun666** [comment]
+1

**Comment by nicejade** [comment]
@everett7623 

可以的。将给定的 Docker 命令转换为 Docker Compose 配置文件，可以这样做：

1. 创建一个 `docker-compose.yml` 文件，并在其中定义服务：

```yaml
version: '3'
services:
  markdown-editor:
    image: nicejade/markdown-online-editor:2.1.0
    ports:
      - "8866:80"
    restart: always
```

2. 解释一下每个部分的含义：
   - `version: '3'` 指定了 Docker Compose 文件的版本。
   - `services` 下面是定义的服务列表，这里只有一个服务 `markdown-editor`。
   - `image: nicejade/markdown-online-editor:2.1.0` 指定了要使用的 Docker 镜像及其版本。
   - `ports` 部分将容器的端口映射到主机上的端口，即将容器的 80 端口映射到主机的 8866 端口（您可以修改为自己喜欢的端口）。
   - `restart: always` 表示容器退出时总是重启。

3. 使用 Docker Compose 启动服务：
   - 在包含 `docker-compose.yml` 文件的目录中，运行以下命令启动服务：
     ```
     docker-compose up -d
     ```

这样，就相当于用 Docker Compose 实现了之前用 `docker run` 命令启动的容器服务。

---

温馨提醒，如果您机器上的 Docker Compose 是 `2.*`， 需要将上述 yml 配置的 `version: '3'` 修改为 `version: '2'`。
